---
  title: "Passos para inscrição no PAEI"
---
  
  
  
#### 1) Complete a Inscrição para Admissão

* É necessário enviar carta de recomendação assinada, histórico escolar do ano corrente ou do ano anterior cursado e carta de recomendação de um professor atestando aptidões acadêmicas.

* Acesse a Inscrição PAEI 2024 clicando no botão [Inscreva-se aqui](https://forms.gle/fqZtzptuU2NJ64gQ7)

#### 2) Faça um investimento no programa

* Para a participação no programa, é necessário investir o valor de R$ 30 como taxa de inscrição.

* Chave PIX: csistersfonseca@hotmail.com (favorecido: Gepoliano dos Santos Chaves)

* Observe que o portal de pagamento é um sistema separado do portal de aplicações.
Por favor informar o nome do estudante favorecido no momento do pagamento do investimento no programa.

* Uma taxa de inscrição não reembolsável de R$ 30 é necessária para que a inscrição seja considerada completa e revisada para admissão. Se precisar de apoio financeiro, envie um e-mail para recombio@dnabrasil.dev.br com uma ou duas frases explicando a necessidade, e poderá ser concedida isenção de taxa de inscrição.

* Caso tenha interesse no auxílio para a candidatura ao SIP no campus da UCSC, será necessário investimento de US$ 100.  A candidatura ao SIP por meio do PAEI auxilia no pleito de bolsas de alojamento, alimentação e taxas escolares nos valores de 25%, 50%, 75% e 100%, junto à UCSC.



#### 3) Peça a carta de recomendação ao seu professor

* É necessária uma referência de um professor ou mentor que conheça bem você e sua aptidão acadêmica para que sua inscrição no PAEI seja considerada completa.

* As instruções para enviar o Formulário de Referência do Professor ao seu professor estão na Seção Dois do Pedido de Admissão PAEI 2024 com link acima.

* É uma ótima ideia identificar o mais rápido possível o professor que será sua referência e receber o formulário de referência do professor o mais rápido possível, para que tenham o máximo de tempo possível para completar sua referência.
Assim que o Formulário de Referência do Professor for enviado ao professor ou mentor que você identificou, você receberá um e-mail de confirmação, que incluirá instruções sobre como alterar sua referência caso a primeira referência que você identificou não consiga completar a referência, afinal.

* Assim que o professor ou mentor concluir e enviar a referência em seu nome, você receberá um e-mail de confirmação.