---
  title: "Integração de dados Genômicos ao Sistema de Saúde Público Brasileiro (SUS)"
---

\

Pretende-se que ferramentas úteis ao sistema público de saúde brasileiro sejam desenvolvidas colaborativamente usando o [Lab PmD](lab-virtual.html) e disponibilizadas por meio da [plataforma GERALDA](https://geraldo-br.netlify.app/pmd).

\

### Atividades Planejadas

\

Temas propostos

* Extração de DNA

* Aplicação do DNA recombinante para a obtenção de transgênicos 

* **Banco de dados** 

* **Alinhamento genético**

\

Instrutores responsáveis

* Dr. Gepoliano Chaves

* Dr. Wagner Macena

* Dr. Sebastião Rodrigo

* Dra. Lívia Lemos


\


#### Desenvolvimento Colaborativo

\

O desenvolvimento de *software* é possibilitado por meio de vídeos instrucionais:

\

* Servidor computacional e arquivo fastq 
  + [pseudo-código](https://docs.google.com/document/d/1TBsntWO8cCpHQ9YkvlUwXkXHqAkoKPlVBxtltosAAPs/edit?tab=t.0#heading=h.sc3873h8qqnu) | [instruções para gravação de vídeo](https://docs.google.com/document/d/161PbOhDUD06T_ALjTlTGr_N2WFCFryxUf2OS1HtTWro/edit?usp=sharing) | [vídeo](https://drive.google.com/file/d/1FYhk2wx59oGGtiQwGLOjLbkj48nBlq9v/view?usp=sharing) | [notebook](https://bioinformatics-bridge-course.netlify.app/align-extract-counts#download-fastq-file)
  
\
  
#### Atividades para estudantes

\

* 28/04/2025: Leitura de [Artigo sobre DNA recombinante, 2016](https://drive.google.com/file/d/1F1fUyGFlYZkSJw10gLZdUVN5DwoLO29s/view?usp=sharing)

* 28/04/2025: Leitura de [Como construir atividades colaborativamente mostrando scripts, 2016](https://drive.google.com/file/d/1F1fUyGFlYZkSJw10gLZdUVN5DwoLO29s/view?usp=sharing)

* 30/04/2025: Catalogação de genealogias brasileiras através da geração de **banco de dados**

* 05/05/25 e 05/08/25: Atividades de **Alinhamento genético** e bioinformática

\

#### Encontros

\

24/04/25 | Quinta-feira, 14h - Extração de DNA: [Slides](https://docs.google.com/presentation/d/1CDvot01DESUGmTz_N9yecDO7wTh2dm7u/edit?usp=sharing&ouid=118102085428546980704&rtpof=true&sd=true), [Parte 1](https://drive.google.com/file/d/1yRgUjFW8coLZmfc8rLnv7_xxY3PTrxvT/view?usp=sharing) e [Parte 2](https://drive.google.com/file/d/1m0-i0MOAqLjl18Iyx9wQClLGBm9REkLV/view?usp=sharing) \
28/04/25 | Segunda-feira, 14h - Aplicação do DNA recombinante para a obtenção de transgênicos: [Estudo direcionado de artigo](https://www.nature.com/scitable/topicpage/recombinant-dna-technology-and-transgenic-animals-34513/) \
05/05/25 | Segunda-feira às 14h: [**Banco de dados**](https://docs.google.com/presentation/d/1xQn8HpktC6X_vY-EUfFcSA8dia70pMxj/edit?usp=sharing&ouid=103625408686346070691&rtpof=true&sd=true)\
05/08/25 | Quinta-feira às  14h: [**Alinhamento genético**](https://bioinfo-ufsb-website.netlify.app/alinhamento_analise_sequencias)








