---
  title: "Pesquisa na Modalidade à Distância (PmD)"
---

\

### Experiências prévias

\

Baseado na atuação do Dr. Raja GuhaThakurta e do Dr. Gepoliano Chaves no *Science Internship Program* (SIP), o PAEI disponibiliza a [pesquisa real na modalidade à distância](https://www.youtube.com/watch?v=Z0WTzVNB2g4) para a Educação, Ciência e Tecnologia brasileiras.



A pesquisa real na modalidade à distância (PmD) visa contribuir para o avanço científico na fronteira do conhecimento, como a pesquisa real regular, fazendo porém uso de tecnologias que não necessitam de contato presencial como na pesquisa acadêmica regular.

\

### Exemplos de Pesquisa Real à Distância

#### *Science Internship Program* (SIP)

* O SIP adotou a PmD durante a pandemia de SARS-CoV-2 a partir de 2020. 

* Há práticas para a educação à distância que permitem maior eficiência no processo de implementação da PmD. 
  - [Métodos de pesquisa na educação à distância](https://www.aritzhaupt.com/distance_education/research-methods/)


#### *Treehouse Undergraduate Bioinformatics Internship* (TUBI)

* Programa de imersão em bioinformática do Instituto de Genômica da UCSC, desenvolvido pelo laboratório da Dra. Olena Vaske

* Tem como objetivo contribuir para o progresso e uso da genômica de cânceres pediátricos.

#### PAEI

* Nasce como uma implementação da PmD como consequência do caráter tecnológico das ciências genômicas no que se refere às linguagens de programação computacional.

* Para tanto, mentores, empreendedores e estudantes colaboram no desenvolvimento e compartilhamento de código-fonte.

* Instruções para o compartilhamento de código-fonte podem ser encontradas no seguinte *link*: 
  -  [Compartilhamento de código fonte (OneDrive)](https://tinyurl.com/gitCorndel)
  -  [Compartilhamento de código fonte (Google drive)](https://drive.google.com/file/d/1ouj3EQbKzh60pYNbqeOxHkJKJAa4BnwW/view?usp=sharing)

#### PmD no Brasil

A pesquisa na modalidade à distância é objeto de investimentos da Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (CAPES). A diretoria responsável é a Diretoria de Educação à Distância (DED).
https://www.youtube.com/watch?v=5mjVZ_oLczo&t=2s

Em trabalhos como "*Leading the e-Learning Transformation of Higher Education [OP]: Meeting the Challenges of Technology and Distance Education*", do Dr. Lawrence Ragan, pode-se entender como liderar o progresso na pesquisa e ciência no nível superior para impactar positivamente a educação, ciência e tecnologia brasileiras.