---
  title: "Redes de Novação e Empreendedorismo"
---

\

### Oportunidade para Pesquisadores Brasileiros no Brasil ou Exterior Buscando Inovação ou Empreendedorismo Internacional

\

As portarias de novação [CNPq, de 15 de dezembro de 2023](https://www.in.gov.br/en/web/dou/-/portaria-cnpq-n-1.594-de-15-de-dezembro-de-2023-531778458?fbclid=IwAR3yYTPMuyG_nY0lGTujLU9Dwgo2o7pl7OpqHSBs6WEIkgGQ61tfO10qrqE) e [CAPES, de 19 de dezembro de 2023](http://cad.capes.gov.br/ato-administrativo-detalhar?idAtoAdmElastic=13822), estabeleceram a oportunidade de ex-bolsistas que fizeram pós-graduação no exterior contribuírem para o avanço da Educação Básica, Ciência, Tecnologia e Inovação brasileiras a partir do exterior.

\

Através da parceria entre o PAEI e o Inc∑ption International Fellowship Program, buscamos estabelecer mecanismos que cooperem com o desenvolvimento da Educação, CT&I brasileiras através da internacionalização e empreendedorismo. O Programa Inc∑ption visa desenvolver startups internacionais de deep tech sediadas nos EUA.
O desenvolvimento e a implementação de cada solução ocorrem simultaneamente nos EUA e no Brasil, para benefício de ambas as nações.

\

É essencial ressaltar que esse Programa é uma iniciativa piloto e ainda não publicamente disponível. Sou um dos beneficiários do Programa e obtive o meu projeto de Novação aprovado também por esse motivo. Não é necessário ter nenhum conhecimento prévio ou ter uma idéia de startup para explorar essa oportunidade.


\

Saiba mais sobre iniciativas entre ex-bolsistas brasileiros no exterior que visam estabelecer redes de colaboração internacional através do empreendedorismo e intercâmbio acadêmicos visitando os *link* abaixo.



\

### Iniciativas para intercâmbio de pesquisadores brasileiros

\

* [Inscreva-se para explorar sua participação nesta oportunidade](https://forms.gle/c7FLFGehWEyBReas7)

\

O Programa já conta com a colaboração de instituições no Brasil como unidades do SENAI e parques tecnológicos como Itaipu Parquetec e o Parque Tecnológico de São José dos Campos (PIT).

\

Estamos buscando pesquisadores brasileiros no Brasil ou no exterior com interesse em explorar a criação de novos produtos ou startups com foco internacional. Ex-bolsistas Ciência Sem Fronteira podem ter seu projeto de Novação aprovado por vínculo a essa iniciativa. Não há nenhum custo de inscrição e haverá oportunidade de remuneração, incluindo participação societária. 

\

Esse é uma iniciativa internacional envolvendo os EUA e o Brasil, podendo haver integração de outros países. Essa iniciativa é em parceria com a linha de cooperação internacional da Embrapii, incluindo seus 93 centros credenciados e diferentes estados nos EUA. 

\

Essa chamada inicia-se agora e continuará de forma contínua, sempre buscando matches com startups e parceiros corporativos. Por favor, nos informe se sua situação mudar em relação a sua disponibilidade e/ou interesse de participar dessa seleção, para que possamos remover seu cadastro de potenciais matches futuros.
